name: Proof of Twitter tests
on: [push]
env:
  VITE_CONTRACT_ADDRESS: ${{ vars.VITE_CONTRACT_ADDRESS }}
  VITE_CIRCUIT_ARTIFACTS_URL: ${{ vars.VITE_CIRCUIT_ARTIFACTS_URL }}
jobs:
  run_circuit_tests:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3

      # Circom installation from https://github.com/erhant/circomkit/blob/main/.github/workflows/tests.yml
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes \
            build-essential \
            libgmp-dev \
            libsodium-dev \
            nasm \
            nlohmann-json3-dev

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Download Circom Binary v2.1.6
        run: |
          wget -qO /home/runner/work/circom https://github.com/iden3/circom/releases/download/v2.1.6/circom-linux-amd64
          chmod +x /home/runner/work/circom
          sudo mv /home/runner/work/circom /bin/circom

      - name: Print Circom version
        run: circom --version
          
      - name: Install Yarn dependencies
        working-directory: ./packages/circuits
        run: yarn install --immutable
        
      - name: Run Tests
        working-directory: ./packages/circuits
        run: yarn test

  run_contract_tests:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Install Yarn dependencies
        working-directory: ./packages/contracts
        run: yarn install --immutable
      - name: Run Tests
        run: forge test --root ./packages/contracts

  run_app_unit_and_e2e_tests:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      - name: Install Yarn dependencies
        working-directory: ./packages/app
        run: yarn install
      - name: Run test
        working-directory: ./packages/app
        run: yarn test
      - name: Run build
        working-directory: ./packages/app
        run: yarn build
      - name: E2E Test Code
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          CI: "true"
        with:
          args: yarn workspace @zk-email/twitter-verifier-app test:full-e2e
      
